// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package io.digitalbits.sdk.xdr;


import java.io.IOException;


// === xdr source ============================================================

//  enum DigitalBitsValueType
//  {
//      DIGITALBITS_VALUE_BASIC = 0,
//      DIGITALBITS_VALUE_SIGNED = 1
//  };

//  ===========================================================================
public enum DigitalBitsValueType implements XdrElement {
  DIGITALBITS_VALUE_BASIC(0),
  DIGITALBITS_VALUE_SIGNED(1),
  ;
  private int mValue;

  DigitalBitsValueType(int value) {
      mValue = value;
  }

  public int getValue() {
      return mValue;
  }

  public static DigitalBitsValueType decode(XdrDataInputStream stream) throws IOException {
    int value = stream.readInt();
    switch (value) {
      case 0: return DIGITALBITS_VALUE_BASIC;
      case 1: return DIGITALBITS_VALUE_SIGNED;
      default:
        throw new RuntimeException("Unknown enum value: " + value);
    }
  }

  public static void encode(XdrDataOutputStream stream, DigitalBitsValueType value) throws IOException {
    stream.writeInt(value.getValue());
  }

  public void encode(XdrDataOutputStream stream) throws IOException {
    encode(stream, this);
  }
}
